version: 2

jobs:
  test_node_6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Testing for NodeJs 6
          command: npm run test

  test_node_10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Unit Testing for NodeJs 10
          command: npm run test

workflows:
  version: 2
  test-release:
    jobs:
      - test_node_6
      - test_node_10
